apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-iclab
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-iclab
  targetCPUUtilizationPercentage: 50
