apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-iclab
    exercise: k8s
  name: ms-iclab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-iclab
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ms-iclab
    spec:
      containers:
      - image: rodrigoghm/ms-iclab:1.0.0
        name: ms-iclab
        ports:
          - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /rest/mscovid/test?msg=testing
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: version-java
          value: "17.0.6"
        envFrom:
          - configMapRef:
              name: cfg-app
        envFrom:
          - secretRef:
              name: integrantes
        resources: {}
status: {}
