apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ms-iclab
    exercise: k8s
  name: ms-iclab
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: ms-iclab
  type: ClusterIP
status:
  loadBalancer: {}
